import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from engine import runner

PROB_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "problems")

REFERENCE_PY = {
    "pair_sum_indices": "def pairSumIndices(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        if target - n in seen:\n            return [seen[target-n], i]\n        seen[n] = i\n    return []\n",
    "best_trade_window": "def maxProfit(prices):\n    lo = float('inf'); best = 0\n    for p in prices:\n        lo = min(lo, p)\n        best = max(best, p - lo)\n    return best\n",
    "max_subarray_sum": "def maxSubArray(nums):\n    best = cur = nums[0]\n    for n in nums[1:]:\n        cur = max(n, cur + n)\n        best = max(best, cur)\n    return best\n",
    "grid_min_steps": "from collections import deque\ndef minSteps(grid):\n    rows, cols = len(grid), len(grid[0])\n    if grid[0][0] == 1 or grid[rows-1][cols-1] == 1:\n        return -1\n    if rows == 1 and cols == 1:\n        return 0\n    q = deque([(0,0,0)])\n    seen = {(0,0)}\n    while q:\n        r,c,d = q.popleft()\n        for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:\n            nr,nc = r+dr,c+dc\n            if 0<=nr<rows and 0<=nc<cols and (nr,nc) not in seen and grid[nr][nc]==0:\n                if nr==rows-1 and nc==cols-1:\n                    return d+1\n                seen.add((nr,nc))\n                q.append((nr,nc,d+1))\n    return -1\n",
    "network_delay_dijkstra": "import heapq\ndef shortestDelays(n, edges, src):\n    graph = [[] for _ in range(n)]\n    for u,v,w in edges:\n        graph[u].append((v,w))\n    dist = [float('inf')]*n\n    dist[src] = 0\n    pq = [(0, src)]\n    while pq:\n        d,u = heapq.heappop(pq)\n        if d > dist[u]: continue\n        for v,w in graph[u]:\n            if d+w < dist[v]:\n                dist[v] = d+w\n                heapq.heappush(pq, (d+w, v))\n    return [d if d != float('inf') else -1 for d in dist]\n",
    "valid_bracket_sequence": "def isValidBrackets(s):\n    pairs = {')':'(', ']':'[', '}':'{'}\n    stack = []\n    for c in s:\n        if c in '([{':\n            stack.append(c)\n        elif c in pairs:\n            if not stack or stack.pop() != pairs[c]:\n                return False\n    return not stack\n",
    "min_coins_for_amount": "def minCoins(coins, amount):\n    INF = float('inf')\n    dp = [0] + [INF]*amount\n    for a in range(1, amount+1):\n        for c in coins:\n            if c <= a:\n                dp[a] = min(dp[a], dp[a-c]+1)\n    return dp[amount] if dp[amount] != INF else -1\n",
    "tree_max_depth": "def maxDepth(root):\n    if root is None:\n        return 0\n    return 1 + max(maxDepth(root.left), maxDepth(root.right))\n",
    "rotate_array_k": "def rotateArray(nums, k):\n    n = len(nums)\n    k %= n\n    return nums[-k:] + nums[:-k] if k else nums[:]\n",
    "merge_overlapping_intervals": "def mergeIntervals(intervals):\n    intervals = sorted(intervals)\n    out = []\n    for iv in intervals:\n        if out and iv[0] <= out[-1][1]:\n            out[-1][1] = max(out[-1][1], iv[1])\n        else:\n            out.append(iv[:])\n    return out\n",
    "count_islands": "def countIslands(grid):\n    rows, cols = len(grid), len(grid[0])\n    grid = [row[:] for row in grid]\n    def sink(r,c):\n        if r<0 or c<0 or r>=rows or c>=cols or grid[r][c]!=1: return\n        grid[r][c]=0\n        sink(r+1,c); sink(r-1,c); sink(r,c+1); sink(r,c-1)\n    count=0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c]==1:\n                count+=1\n                sink(r,c)\n    return count\n",
    "longest_substring_k_distinct": "def longestKDistinct(s, k):\n    if k == 0: return 0\n    from collections import defaultdict\n    count = defaultdict(int)\n    left = 0; best = 0\n    for right, ch in enumerate(s):\n        count[ch]+=1\n        while len(count) > k:\n            count[s[left]] -= 1\n            if count[s[left]] == 0:\n                del count[s[left]]\n            left += 1\n        best = max(best, right-left+1)\n    return best\n",

    "shortest_word_distance": "def shortestWordDistance(wordsDict, word1, word2):\n    i1=i2=-1\n    best=float('inf')\n    for i,w in enumerate(wordsDict):\n        if w==word1: i1=i\n        if w==word2: i2=i\n        if i1!=-1 and i2!=-1: best=min(best, abs(i1-i2))\n    return best\n",
    "move_zeroes": "def moveZeroes(nums):\n    res=[x for x in nums if x!=0]\n    res += [0]*(len(nums)-len(res))\n    return res\n",
    "course_schedule_ii": "import heapq\ndef courseOrder(numCourses, prerequisites):\n    graph=[[] for _ in range(numCourses)]\n    indeg=[0]*numCourses\n    for a,b in prerequisites:\n        graph[b].append(a); indeg[a]+=1\n    heap=[i for i in range(numCourses) if indeg[i]==0]\n    heapq.heapify(heap)\n    order=[]\n    while heap:\n        u=heapq.heappop(heap)\n        order.append(u)\n        for v in graph[u]:\n            indeg[v]-=1\n            if indeg[v]==0: heapq.heappush(heap,v)\n    return order if len(order)==numCourses else []\n",
    "heaters": "import bisect\ndef findRadius(houses, heaters):\n    heaters=sorted(heaters)\n    ans=0\n    for h in houses:\n        idx=bisect.bisect_left(heaters,h)\n        dist=float('inf')\n        if idx<len(heaters): dist=min(dist, heaters[idx]-h)\n        if idx>0: dist=min(dist, h-heaters[idx-1])\n        ans=max(ans,dist)\n    return ans\n",
    "daily_temperatures": "def dailyTemperatures(temperatures):\n    res=[0]*len(temperatures)\n    stack=[]\n    for i,t in enumerate(temperatures):\n        while stack and temperatures[stack[-1]]<t:\n            j=stack.pop(); res[j]=i-j\n        stack.append(i)\n    return res\n",
    "string_compression": "def compress(s):\n    if not s: return ''\n    res=[]\n    i=0; n=len(s)\n    while i<n:\n        j=i\n        while j<n and s[j]==s[i]: j+=1\n        cnt=j-i\n        res.append(s[i])\n        if cnt>1: res.append(str(cnt))\n        i=j\n    return ''.join(res)\n",
    "points_inside_circle_queries": "def countPoints(points, queries):\n    res=[]\n    for x,y,r in queries:\n        c=0\n        for px,py in points:\n            if (px-x)**2+(py-y)**2<=r*r: c+=1\n        res.append(c)\n    return res\n",
    "binary_tree_vertical_order": "from collections import deque, defaultdict\ndef verticalOrder(root):\n    if not root: return []\n    cols=defaultdict(list)\n    q=deque([(root,0)])\n    while q:\n        node,col=q.popleft()\n        cols[col].append(node.val)\n        if node.left: q.append((node.left,col-1))\n        if node.right: q.append((node.right,col+1))\n    return [cols[c] for c in sorted(cols)]\n",
    "push_dominoes": "def pushDominoes(dominoes):\n    s='L'+dominoes+'R'\n    res=list(s)\n    prev=0\n    for i in range(1,len(s)):\n        c=s[i]\n        if c=='.': continue\n        if s[prev]==c:\n            for k in range(prev+1,i): res[k]=c\n        elif s[prev]=='L' and c=='R':\n            pass\n        else:\n            lo,hi=prev+1,i-1\n            while lo<hi:\n                res[lo]='R'; res[hi]='L'; lo+=1; hi-=1\n        prev=i\n    return ''.join(res[1:-1])\n",
    "group_anagrams": "from collections import defaultdict\ndef groupAnagrams(strs):\n    groups=defaultdict(list)\n    for s in strs:\n        key=''.join(sorted(s))\n        groups[key].append(s)\n    return list(groups.values())\n",
    "flip_equivalent_binary_trees": "def flipEquiv(root1, root2):\n    if root1 is None and root2 is None: return True\n    if root1 is None or root2 is None: return False\n    if root1.val != root2.val: return False\n    return (flipEquiv(root1.left, root2.left) and flipEquiv(root1.right, root2.right)) or (flipEquiv(root1.left, root2.right) and flipEquiv(root1.right, root2.left))\n",
    "flatten_binary_tree_preorder": "def flattenPreorder(root):\n    res=[]\n    def dfs(node):\n        if not node: return\n        res.append(node.val); dfs(node.left); dfs(node.right)\n    dfs(root)\n    return res\n",
    "search_suggestions_system": "def suggestedProducts(products, searchWord):\n    products=sorted(products)\n    res=[]\n    prefix=''\n    for ch in searchWord:\n        prefix+=ch\n        matches=[p for p in products if p.startswith(prefix)][:3]\n        res.append(matches)\n    return res\n",
    "game_of_life": "def gameOfLife(board):\n    rows=len(board); cols=len(board[0])\n    def count_live(r,c):\n        cnt=0\n        for dr in (-1,0,1):\n            for dc in (-1,0,1):\n                if dr==0 and dc==0: continue\n                nr,nc=r+dr,c+dc\n                if 0<=nr<rows and 0<=nc<cols and board[nr][nc]==1: cnt+=1\n        return cnt\n    new=[[0]*cols for _ in range(rows)]\n    for r in range(rows):\n        for c in range(cols):\n            live=count_live(r,c)\n            if board[r][c]==1: new[r][c]=1 if live in (2,3) else 0\n            else: new[r][c]=1 if live==3 else 0\n    return new\n",
    "course_schedule": "from collections import deque\ndef canFinish(numCourses, prerequisites):\n    graph=[[] for _ in range(numCourses)]\n    indeg=[0]*numCourses\n    for a,b in prerequisites:\n        graph[b].append(a); indeg[a]+=1\n    q=deque([i for i in range(numCourses) if indeg[i]==0])\n    seen=0\n    while q:\n        u=q.popleft(); seen+=1\n        for v in graph[u]:\n            indeg[v]-=1\n            if indeg[v]==0: q.append(v)\n    return seen==numCourses\n",
    "shortest_word_distance_ii": "from collections import defaultdict\ndef wordDistanceQueries(wordsDict, queries):\n    pos=defaultdict(list)\n    for i,w in enumerate(wordsDict): pos[w].append(i)\n    res=[]\n    for w1,w2 in queries:\n        p1=pos[w1]; p2=pos[w2]\n        i=j=0; best=float('inf')\n        while i<len(p1) and j<len(p2):\n            best=min(best, abs(p1[i]-p2[j]))\n            if p1[i]<p2[j]: i+=1\n            else: j+=1\n        res.append(best)\n    return res\n",
    "search_rotated_sorted_array": "def searchRotated(nums, target):\n    lo,hi=0,len(nums)-1\n    while lo<=hi:\n        mid=(lo+hi)//2\n        if nums[mid]==target: return mid\n        if nums[lo]<=nums[mid]:\n            if nums[lo]<=target<nums[mid]: hi=mid-1\n            else: lo=mid+1\n        else:\n            if nums[mid]<target<=nums[hi]: lo=mid+1\n            else: hi=mid-1\n    return -1\n",
    "snakes_and_ladders": "from collections import deque\ndef snakesAndLadders(board):\n    n=len(board)\n    def get_val(s):\n        r=(s-1)//n; c=(s-1)%n\n        if r%2==1: c=n-1-c\n        row=n-1-r\n        return board[row][c]\n    dist=[-1]*(n*n+1)\n    dist[1]=0\n    q=deque([1])\n    while q:\n        cur=q.popleft()\n        if cur==n*n: return dist[cur]\n        for nxt in range(cur+1, min(cur+6, n*n)+1):\n            dest=get_val(nxt)\n            dest=dest if dest!=-1 else nxt\n            if dist[dest]==-1:\n                dist[dest]=dist[cur]+1\n                q.append(dest)\n    return -1 if dist[n*n]==-1 else dist[n*n]\n",
    "find_duplicate_number": "def findDuplicate(nums):\n    slow=fast=nums[0]\n    while True:\n        slow=nums[slow]; fast=nums[nums[fast]]\n        if slow==fast: break\n    slow2=nums[0]\n    while slow2!=slow:\n        slow2=nums[slow2]; slow=nums[slow]\n    return slow\n",
    "time_based_key_value_store": "from collections import defaultdict\ndef timeMapOperations(operations):\n    store=defaultdict(list)\n    res=[]\n    for op in operations:\n        if op[0]=='set':\n            _,key,value,ts=op\n            store[key].append((int(ts), value))\n        else:\n            _,key,ts=op\n            ts=int(ts)\n            arr=store.get(key,[])\n            lo,hi=0,len(arr)-1\n            ans=''\n            while lo<=hi:\n                mid=(lo+hi)//2\n                if arr[mid][0]<=ts: ans=arr[mid][1]; lo=mid+1\n                else: hi=mid-1\n            res.append(ans)\n    return res\n",
    "spiral_matrix": "def spiralOrder(matrix):\n    res=[]\n    if not matrix: return res\n    top,bottom=0,len(matrix)-1\n    left,right=0,len(matrix[0])-1\n    while top<=bottom and left<=right:\n        for c in range(left,right+1): res.append(matrix[top][c])\n        top+=1\n        for r in range(top,bottom+1): res.append(matrix[r][right])\n        right-=1\n        if top<=bottom:\n            for c in range(right,left-1,-1): res.append(matrix[bottom][c])\n            bottom-=1\n        if left<=right:\n            for r in range(bottom,top-1,-1): res.append(matrix[r][left])\n            left+=1\n    return res\n",
    "video_stitching": "def videoStitching(clips, time):\n    clips=sorted(clips)\n    n=len(clips)\n    i=0; count=0; cur_end=0; farthest=0\n    while cur_end<time:\n        while i<n and clips[i][0]<=cur_end:\n            farthest=max(farthest, clips[i][1]); i+=1\n        if farthest<=cur_end: return -1\n        count+=1; cur_end=farthest\n    return count\n",
    "minesweeper_reveal": "def updateBoard(board, click):\n    board=[row[:] for row in board]\n    r0,c0=click\n    rows,cols=len(board),len(board[0])\n    if board[r0][c0]=='M':\n        board[r0][c0]='X'; return board\n    dirs=[(-1,-1),(-1,0),(-1,1),(0,-1),(0,1),(1,-1),(1,0),(1,1)]\n    def count_mines(r,c):\n        cnt=0\n        for dr,dc in dirs:\n            nr,nc=r+dr,c+dc\n            if 0<=nr<rows and 0<=nc<cols and board[nr][nc]=='M': cnt+=1\n        return cnt\n    stack=[(r0,c0)]\n    visited=set()\n    while stack:\n        r,c=stack.pop()\n        if (r,c) in visited: continue\n        visited.add((r,c))\n        if board[r][c]!='E': continue\n        cnt=count_mines(r,c)\n        if cnt>0: board[r][c]=str(cnt)\n        else:\n            board[r][c]='B'\n            for dr,dc in dirs:\n                nr,nc=r+dr,c+dc\n                if 0<=nr<rows and 0<=nc<cols and (nr,nc) not in visited: stack.append((nr,nc))\n    return board\n",
    "number_of_distinct_islands": "def numDistinctIslands(grid):\n    rows,cols=len(grid),len(grid[0])\n    grid=[row[:] for row in grid]\n    shapes=set()\n    def dfs(r,c,r0,c0,path):\n        if r<0 or c<0 or r>=rows or c>=cols or grid[r][c]!=1: return\n        grid[r][c]=0\n        path.append((r-r0,c-c0))\n        dfs(r+1,c,r0,c0,path); dfs(r-1,c,r0,c0,path); dfs(r,c+1,r0,c0,path); dfs(r,c-1,r0,c0,path)\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c]==1:\n                path=[]\n                dfs(r,c,r,c,path)\n                shapes.add(tuple(path))\n    return len(shapes)\n",
    "rotting_oranges": "from collections import deque\ndef orangesRotting(grid):\n    rows,cols=len(grid),len(grid[0])\n    grid=[row[:] for row in grid]\n    q=deque()\n    fresh=0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c]==2: q.append((r,c,0))\n            elif grid[r][c]==1: fresh+=1\n    mins=0\n    while q:\n        r,c,t=q.popleft()\n        mins=max(mins,t)\n        for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr,nc=r+dr,c+dc\n            if 0<=nr<rows and 0<=nc<cols and grid[nr][nc]==1:\n                grid[nr][nc]=2; fresh-=1; q.append((nr,nc,t+1))\n    return mins if fresh==0 else -1\n",
    "meeting_rooms_ii": "def minMeetingRooms(intervals):\n    starts=sorted(i[0] for i in intervals)\n    ends=sorted(i[1] for i in intervals)\n    rooms=0; end_ptr=0\n    for s in starts:\n        if s<ends[end_ptr]: rooms+=1\n        else: end_ptr+=1\n    return rooms\n",
    "min_rounds_complete_tasks": "from collections import Counter\nimport math\ndef minimumRounds(tasks):\n    cnt=Counter(tasks)\n    rounds=0\n    for c in cnt.values():\n        if c==1: return -1\n        rounds+=math.ceil(c/3)\n    return rounds\n",
    "evaluate_rpn": "def evalRPN(tokens):\n    stack=[]\n    for t in tokens:\n        if t in ('+','-','*','/'):\n            b=stack.pop(); a=stack.pop()\n            if t=='+': stack.append(a+b)\n            elif t=='-': stack.append(a-b)\n            elif t=='*': stack.append(a*b)\n            else: stack.append(int(a/b))\n        else:\n            stack.append(int(t))\n    return stack[-1]\n",
    "making_a_large_island": "def largestIsland(grid):\n    n=len(grid)\n    grid=[row[:] for row in grid]\n    def neighbors(r,c):\n        for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr,nc=r+dr,c+dc\n            if 0<=nr<n and 0<=nc<n: yield nr,nc\n    island_id=2\n    sizes={}\n    for r in range(n):\n        for c in range(n):\n            if grid[r][c]==1:\n                stack=[(r,c)]; grid[r][c]=island_id; size=0\n                while stack:\n                    cr,cc=stack.pop(); size+=1\n                    for nr,nc in neighbors(cr,cc):\n                        if grid[nr][nc]==1:\n                            grid[nr][nc]=island_id; stack.append((nr,nc))\n                sizes[island_id]=size; island_id+=1\n    best=max(sizes.values()) if sizes else 0\n    has_zero=False\n    for r in range(n):\n        for c in range(n):\n            if grid[r][c]==0:\n                has_zero=True\n                seen=set(); total=1\n                for nr,nc in neighbors(r,c):\n                    id_=grid[nr][nc]\n                    if id_>1 and id_ not in seen:\n                        seen.add(id_); total+=sizes[id_]\n                best=max(best,total)\n    if not has_zero: return n*n\n    return best\n",
    "word_break_ii": "def wordBreakSentences(s, wordDict):\n    wordSet=set(wordDict)\n    memo={}\n    def backtrack(start):\n        if start==len(s): return ['']\n        if start in memo: return memo[start]\n        res=[]\n        for end in range(start+1, len(s)+1):\n            word=s[start:end]\n            if word in wordSet:\n                for rest in backtrack(end):\n                    res.append(word if not rest else word+' '+rest)\n        memo[start]=res\n        return res\n    return backtrack(0)\n",
    "median_data_stream_doubled": "import heapq\ndef medianStreamDoubled(nums):\n    small=[]; large=[]; res=[]\n    for num in nums:\n        heapq.heappush(small, -num)\n        heapq.heappush(large, -heapq.heappop(small))\n        if len(large)>len(small): heapq.heappush(small, -heapq.heappop(large))\n        if len(small)>len(large): res.append(-2*small[0])\n        else: res.append(-small[0]+large[0])\n    return res\n",
}

REFERENCE_CPP = {
    "pair_sum_indices": "vector<int> pairSumIndices(vector<int> nums, int target) {\n    unordered_map<int,int> seen;\n    for (int i=0;i<(int)nums.size();++i) {\n        auto it = seen.find(target-nums[i]);\n        if (it != seen.end()) return {it->second, i};\n        seen[nums[i]] = i;\n    }\n    return {};\n}\n",
    "best_trade_window": "int maxProfit(vector<int> prices) {\n    int lo = INT_MAX, best = 0;\n    for (int p : prices) { lo = min(lo, p); best = max(best, p - lo); }\n    return best;\n}\n",
    "max_subarray_sum": "int maxSubArray(vector<int> nums) {\n    int best = nums[0], cur = nums[0];\n    for (size_t i=1;i<nums.size();++i) { cur = max(nums[i], cur+nums[i]); best = max(best, cur); }\n    return best;\n}\n",
    "grid_min_steps": "int minSteps(vector<vector<int>> grid) {\n    int rows = grid.size(), cols = grid[0].size();\n    if (grid[0][0]==1 || grid[rows-1][cols-1]==1) return -1;\n    if (rows==1 && cols==1) return 0;\n    vector<vector<bool>> seen(rows, vector<bool>(cols,false));\n    queue<tuple<int,int,int>> q;\n    q.push({0,0,0}); seen[0][0]=true;\n    int dr[]={1,-1,0,0}, dc[]={0,0,1,-1};\n    while(!q.empty()){\n        auto [r,c,d] = q.front(); q.pop();\n        for(int i=0;i<4;++i){\n            int nr=r+dr[i], nc=c+dc[i];\n            if(nr>=0&&nr<rows&&nc>=0&&nc<cols&&!seen[nr][nc]&&grid[nr][nc]==0){\n                if(nr==rows-1&&nc==cols-1) return d+1;\n                seen[nr][nc]=true;\n                q.push({nr,nc,d+1});\n            }\n        }\n    }\n    return -1;\n}\n",
    "network_delay_dijkstra": "vector<int> shortestDelays(int n, vector<vector<int>> edges, int src) {\n    vector<vector<pair<int,int>>> graph(n);\n    for (auto &e : edges) graph[e[0]].push_back({e[1], e[2]});\n    vector<long long> dist(n, LLONG_MAX);\n    dist[src]=0;\n    priority_queue<pair<long long,int>, vector<pair<long long,int>>, greater<>> pq;\n    pq.push({0,src});\n    while(!pq.empty()){\n        auto [d,u]=pq.top(); pq.pop();\n        if (d>dist[u]) continue;\n        for (auto &[v,w] : graph[u]) {\n            if (d+w < dist[v]) { dist[v]=d+w; pq.push({dist[v],v}); }\n        }\n    }\n    vector<int> out(n);\n    for(int i=0;i<n;++i) out[i] = dist[i]==LLONG_MAX ? -1 : (int)dist[i];\n    return out;\n}\n",
    "valid_bracket_sequence": "bool isValidBrackets(string s) {\n    stack<char> st;\n    for (char c : s) {\n        if (c=='('||c=='['||c=='{') st.push(c);\n        else {\n            if (st.empty()) return false;\n            char top = st.top(); st.pop();\n            if (c==')' && top!='(') return false;\n            if (c==']' && top!='[') return false;\n            if (c=='}' && top!='{') return false;\n        }\n    }\n    return st.empty();\n}\n",
    "min_coins_for_amount": "int minCoins(vector<int> coins, int amount) {\n    vector<int> dp(amount+1, INT_MAX);\n    dp[0]=0;\n    for(int a=1;a<=amount;++a){\n        for(int c: coins){\n            if(c<=a && dp[a-c]!=INT_MAX) dp[a]=min(dp[a], dp[a-c]+1);\n        }\n    }\n    return dp[amount]==INT_MAX? -1 : dp[amount];\n}\n",
    "tree_max_depth": "int maxDepth(TreeNode* root) {\n    if (!root) return 0;\n    return 1 + max(maxDepth(root->left), maxDepth(root->right));\n}\n",
    "rotate_array_k": "vector<int> rotateArray(vector<int> nums, int k) {\n    int n = nums.size();\n    k %= n;\n    rotate(nums.begin(), nums.begin() + (n - k), nums.end());\n    return nums;\n}\n",
    "merge_overlapping_intervals": "vector<vector<int>> mergeIntervals(vector<vector<int>> intervals) {\n    sort(intervals.begin(), intervals.end());\n    vector<vector<int>> out;\n    for (auto &iv : intervals) {\n        if (!out.empty() && iv[0] <= out.back()[1]) out.back()[1] = max(out.back()[1], iv[1]);\n        else out.push_back(iv);\n    }\n    return out;\n}\n",
    "count_islands": "void __sink(vector<vector<int>> &g, int r, int c) {\n    int rows=g.size(), cols=g[0].size();\n    if (r<0||c<0||r>=rows||c>=cols||g[r][c]!=1) return;\n    g[r][c]=0;\n    __sink(g,r+1,c); __sink(g,r-1,c); __sink(g,r,c+1); __sink(g,r,c-1);\n}\nint countIslands(vector<vector<int>> grid) {\n    int rows=grid.size(), cols=grid[0].size(), count=0;\n    for(int r=0;r<rows;++r) for(int c=0;c<cols;++c) if(grid[r][c]==1){ count++; __sink(grid,r,c); }\n    return count;\n}\n",
    "longest_substring_k_distinct": "int longestKDistinct(string s, int k) {\n    if (k==0) return 0;\n    unordered_map<char,int> count;\n    int left=0, best=0;\n    for (int right=0; right<(int)s.size(); ++right) {\n        count[s[right]]++;\n        while ((int)count.size() > k) {\n            count[s[left]]--;\n            if (count[s[left]]==0) count.erase(s[left]);\n            left++;\n        }\n        best = max(best, right-left+1);\n    }\n    return best;\n}\n",

    "shortest_word_distance": "int shortestWordDistance(vector<string> wordsDict, string word1, string word2) {\n    int i1=-1,i2=-1,best=INT_MAX;\n    for(int i=0;i<(int)wordsDict.size();++i){\n        if(wordsDict[i]==word1) i1=i;\n        if(wordsDict[i]==word2) i2=i;\n        if(i1!=-1&&i2!=-1) best=min(best, abs(i1-i2));\n    }\n    return best;\n}\n",
    "move_zeroes": "vector<int> moveZeroes(vector<int> nums) {\n    vector<int> res;\n    for(int x: nums) if(x!=0) res.push_back(x);\n    while((int)res.size()<(int)nums.size()) res.push_back(0);\n    return res;\n}\n",
    "course_schedule_ii": "vector<int> courseOrder(int numCourses, vector<vector<int>> prerequisites) {\n    vector<vector<int>> graph(numCourses);\n    vector<int> indeg(numCourses,0);\n    for(auto &p: prerequisites){ graph[p[1]].push_back(p[0]); indeg[p[0]]++; }\n    priority_queue<int, vector<int>, greater<int>> heap;\n    for(int i=0;i<numCourses;++i) if(indeg[i]==0) heap.push(i);\n    vector<int> order;\n    while(!heap.empty()){\n        int u=heap.top(); heap.pop();\n        order.push_back(u);\n        for(int v: graph[u]){ if(--indeg[v]==0) heap.push(v); }\n    }\n    if((int)order.size()!=numCourses) return {};\n    return order;\n}\n",
    "heaters": "int findRadius(vector<int> houses, vector<int> heaters) {\n    sort(heaters.begin(), heaters.end());\n    int ans=0;\n    for(int h: houses){\n        auto it = lower_bound(heaters.begin(), heaters.end(), h);\n        long long dist = LLONG_MAX;\n        if(it != heaters.end()) dist = min(dist, (long long)(*it - h));\n        if(it != heaters.begin()) dist = min(dist, (long long)(h - *prev(it)));\n        ans = max(ans, (int)dist);\n    }\n    return ans;\n}\n",
    "daily_temperatures": "vector<int> dailyTemperatures(vector<int> temperatures) {\n    vector<int> res(temperatures.size(), 0);\n    vector<int> stack;\n    for(int i=0;i<(int)temperatures.size();++i){\n        while(!stack.empty() && temperatures[stack.back()]<temperatures[i]){\n            int j=stack.back(); stack.pop_back();\n            res[j]=i-j;\n        }\n        stack.push_back(i);\n    }\n    return res;\n}\n",
    "string_compression": "string compress(string s) {\n    if (s.empty()) return \"\";\n    string res;\n    int i=0, n=s.size();\n    while(i<n){\n        int j=i;\n        while(j<n && s[j]==s[i]) j++;\n        int cnt=j-i;\n        res += s[i];\n        if (cnt>1) res += to_string(cnt);\n        i=j;\n    }\n    return res;\n}\n",
    "points_inside_circle_queries": "vector<int> countPoints(vector<vector<int>> points, vector<vector<int>> queries) {\n    vector<int> res;\n    for (auto &q : queries) {\n        long long x=q[0], y=q[1], r=q[2];\n        int c=0;\n        for (auto &p : points) {\n            long long dx=p[0]-x, dy=p[1]-y;\n            if (dx*dx+dy*dy <= r*r) c++;\n        }\n        res.push_back(c);\n    }\n    return res;\n}\n",
    "binary_tree_vertical_order": "vector<vector<int>> verticalOrder(TreeNode* root) {\n    if (!root) return {};\n    map<int, vector<int>> cols;\n    queue<pair<TreeNode*,int>> q;\n    q.push({root,0});\n    while(!q.empty()){\n        auto [node,col] = q.front(); q.pop();\n        cols[col].push_back(node->val);\n        if (node->left) q.push({node->left, col-1});\n        if (node->right) q.push({node->right, col+1});\n    }\n    vector<vector<int>> res;\n    for (auto &[k,v] : cols) res.push_back(v);\n    return res;\n}\n",
    "push_dominoes": "string pushDominoes(string dominoes) {\n    string s = \"L\" + dominoes + \"R\";\n    string res = s;\n    int prev = 0;\n    for (int i=1;i<(int)s.size();++i){\n        char c = s[i];\n        if (c=='.') continue;\n        if (s[prev]==c){\n            for(int k=prev+1;k<i;++k) res[k]=c;\n        } else if (s[prev]=='L' && c=='R') {\n            // stays\n        } else {\n            int lo=prev+1, hi=i-1;\n            while(lo<hi){ res[lo]='R'; res[hi]='L'; lo++; hi--; }\n        }\n        prev = i;\n    }\n    return res.substr(1, res.size()-2);\n}\n",
    "group_anagrams": "vector<vector<string>> groupAnagrams(vector<string> strs) {\n    map<string, vector<string>> groups;\n    for (auto &s : strs) {\n        string key = s;\n        sort(key.begin(), key.end());\n        groups[key].push_back(s);\n    }\n    vector<vector<string>> res;\n    for (auto &[k,v] : groups) res.push_back(v);\n    return res;\n}\n",
    "flip_equivalent_binary_trees": "bool flipEquiv(TreeNode* root1, TreeNode* root2) {\n    if (!root1 && !root2) return true;\n    if (!root1 || !root2) return false;\n    if (root1->val != root2->val) return false;\n    return (flipEquiv(root1->left, root2->left) && flipEquiv(root1->right, root2->right)) ||\n           (flipEquiv(root1->left, root2->right) && flipEquiv(root1->right, root2->left));\n}\n",
    "flatten_binary_tree_preorder": "vector<int> flattenPreorder(TreeNode* root) {\n    vector<int> res;\n    function<void(TreeNode*)> dfs = [&](TreeNode* node) {\n        if (!node) return;\n        res.push_back(node->val);\n        dfs(node->left); dfs(node->right);\n    };\n    dfs(root);\n    return res;\n}\n",
    "search_suggestions_system": "vector<vector<string>> suggestedProducts(vector<string> products, string searchWord) {\n    sort(products.begin(), products.end());\n    vector<vector<string>> res;\n    string prefix;\n    for (char ch : searchWord) {\n        prefix += ch;\n        vector<string> matches;\n        for (auto &p : products) {\n            if (p.size() >= prefix.size() && p.compare(0, prefix.size(), prefix) == 0) {\n                matches.push_back(p);\n                if (matches.size() == 3) break;\n            }\n        }\n        res.push_back(matches);\n    }\n    return res;\n}\n",
    "game_of_life": "vector<vector<int>> gameOfLife(vector<vector<int>> board) {\n    int rows=board.size(), cols=board[0].size();\n    auto countLive = [&](int r, int c) {\n        int cnt=0;\n        for (int dr=-1;dr<=1;++dr) for(int dc=-1;dc<=1;++dc){\n            if (dr==0&&dc==0) continue;\n            int nr=r+dr,nc=c+dc;\n            if (nr>=0&&nr<rows&&nc>=0&&nc<cols&&board[nr][nc]==1) cnt++;\n        }\n        return cnt;\n    };\n    vector<vector<int>> res(rows, vector<int>(cols,0));\n    for(int r=0;r<rows;++r) for(int c=0;c<cols;++c){\n        int live=countLive(r,c);\n        if (board[r][c]==1) res[r][c] = (live==2||live==3) ? 1 : 0;\n        else res[r][c] = (live==3) ? 1 : 0;\n    }\n    return res;\n}\n",
    "course_schedule": "bool canFinish(int numCourses, vector<vector<int>> prerequisites) {\n    vector<vector<int>> graph(numCourses);\n    vector<int> indeg(numCourses,0);\n    for (auto &p : prerequisites) { graph[p[1]].push_back(p[0]); indeg[p[0]]++; }\n    queue<int> q;\n    for (int i=0;i<numCourses;++i) if (indeg[i]==0) q.push(i);\n    int seen=0;\n    while(!q.empty()){\n        int u=q.front(); q.pop(); seen++;\n        for (int v: graph[u]) if (--indeg[v]==0) q.push(v);\n    }\n    return seen==numCourses;\n}\n",
    "shortest_word_distance_ii": "vector<int> wordDistanceQueries(vector<string> wordsDict, vector<vector<string>> queries) {\n    unordered_map<string, vector<int>> pos;\n    for (int i=0;i<(int)wordsDict.size();++i) pos[wordsDict[i]].push_back(i);\n    vector<int> res;\n    for (auto &q : queries) {\n        auto &p1 = pos[q[0]]; auto &p2 = pos[q[1]];\n        int i=0,j=0; int best=INT_MAX;\n        while (i<(int)p1.size() && j<(int)p2.size()) {\n            best = min(best, abs(p1[i]-p2[j]));\n            if (p1[i] < p2[j]) i++; else j++;\n        }\n        res.push_back(best);\n    }\n    return res;\n}\n",
    "search_rotated_sorted_array": "int searchRotated(vector<int> nums, int target) {\n    int lo=0, hi=nums.size()-1;\n    while (lo<=hi) {\n        int mid=(lo+hi)/2;\n        if (nums[mid]==target) return mid;\n        if (nums[lo]<=nums[mid]) {\n            if (nums[lo]<=target && target<nums[mid]) hi=mid-1;\n            else lo=mid+1;\n        } else {\n            if (nums[mid]<target && target<=nums[hi]) lo=mid+1;\n            else hi=mid-1;\n        }\n    }\n    return -1;\n}\n",
    "snakes_and_ladders": "int snakesAndLadders(vector<vector<int>> board) {\n    int n = board.size();\n    auto getVal = [&](int s) {\n        int r=(s-1)/n, c=(s-1)%n;\n        if (r%2==1) c=n-1-c;\n        int row=n-1-r;\n        return board[row][c];\n    };\n    vector<int> dist(n*n+1, -1);\n    dist[1]=0;\n    queue<int> q; q.push(1);\n    while(!q.empty()){\n        int cur=q.front(); q.pop();\n        if (cur==n*n) return dist[cur];\n        for (int nxt=cur+1; nxt<=min(cur+6,n*n); ++nxt) {\n            int dest = getVal(nxt);\n            if (dest==-1) dest=nxt;\n            if (dist[dest]==-1) { dist[dest]=dist[cur]+1; q.push(dest); }\n        }\n    }\n    return dist[n*n];\n}\n",
    "find_duplicate_number": "int findDuplicate(vector<int> nums) {\n    int slow=nums[0], fast=nums[0];\n    do { slow=nums[slow]; fast=nums[nums[fast]]; } while (slow!=fast);\n    int slow2=nums[0];\n    while (slow2!=slow) { slow2=nums[slow2]; slow=nums[slow]; }\n    return slow;\n}\n",
    "time_based_key_value_store": "vector<string> timeMapOperations(vector<vector<string>> operations) {\n    map<string, vector<pair<int,string>>> store;\n    vector<string> res;\n    for (auto &op : operations) {\n        if (op[0]==\"set\") {\n            store[op[1]].push_back({stoi(op[3]), op[2]});\n        } else {\n            int ts = stoi(op[2]);\n            auto &arr = store[op[1]];\n            string ans = \"\";\n            int lo=0, hi=(int)arr.size()-1;\n            while (lo<=hi) {\n                int mid=(lo+hi)/2;\n                if (arr[mid].first<=ts) { ans=arr[mid].second; lo=mid+1; }\n                else hi=mid-1;\n            }\n            res.push_back(ans);\n        }\n    }\n    return res;\n}\n",
    "spiral_matrix": "vector<int> spiralOrder(vector<vector<int>> matrix) {\n    vector<int> res;\n    if (matrix.empty()) return res;\n    int top=0, bottom=matrix.size()-1, left=0, right=matrix[0].size()-1;\n    while (top<=bottom && left<=right) {\n        for (int c=left;c<=right;++c) res.push_back(matrix[top][c]);\n        top++;\n        for (int r=top;r<=bottom;++r) res.push_back(matrix[r][right]);\n        right--;\n        if (top<=bottom) { for (int c=right;c>=left;--c) res.push_back(matrix[bottom][c]); bottom--; }\n        if (left<=right) { for (int r=bottom;r>=top;--r) res.push_back(matrix[r][left]); left++; }\n    }\n    return res;\n}\n",
    "video_stitching": "int videoStitching(vector<vector<int>> clips, int time) {\n    sort(clips.begin(), clips.end());\n    int n=clips.size(), i=0, count=0, curEnd=0, farthest=0;\n    while (curEnd<time) {\n        while (i<n && clips[i][0]<=curEnd) { farthest=max(farthest, clips[i][1]); i++; }\n        if (farthest<=curEnd) return -1;\n        count++; curEnd=farthest;\n    }\n    return count;\n}\n",
    "minesweeper_reveal": "vector<vector<string>> updateBoard(vector<vector<string>> board, vector<int> click) {\n    int r0=click[0], c0=click[1];\n    int rows=board.size(), cols=board[0].size();\n    if (board[r0][c0]==\"M\") { board[r0][c0]=\"X\"; return board; }\n    int dr[]={-1,-1,-1,0,0,1,1,1};\n    int dc[]={-1,0,1,-1,1,-1,0,1};\n    auto countMines = [&](int r,int c){\n        int cnt=0;\n        for (int k=0;k<8;++k){\n            int nr=r+dr[k], nc=c+dc[k];\n            if (nr>=0&&nr<rows&&nc>=0&&nc<cols&&board[nr][nc]==\"M\") cnt++;\n        }\n        return cnt;\n    };\n    vector<vector<bool>> visited(rows, vector<bool>(cols,false));\n    vector<pair<int,int>> stack = {{r0,c0}};\n    while(!stack.empty()){\n        auto [r,c] = stack.back(); stack.pop_back();\n        if (visited[r][c]) continue;\n        visited[r][c]=true;\n        if (board[r][c]!=\"E\") continue;\n        int cnt=countMines(r,c);\n        if (cnt>0) board[r][c]=to_string(cnt);\n        else {\n            board[r][c]=\"B\";\n            for (int k=0;k<8;++k){\n                int nr=r+dr[k], nc=c+dc[k];\n                if (nr>=0&&nr<rows&&nc>=0&&nc<cols&&!visited[nr][nc]) stack.push_back({nr,nc});\n            }\n        }\n    }\n    return board;\n}\n",
    "number_of_distinct_islands": "int numDistinctIslands(vector<vector<int>> grid) {\n    int rows=grid.size(), cols=grid[0].size();\n    set<string> shapes;\n    function<void(int,int,int,int,vector<vector<int>>&,string&)> dfs = [&](int r,int c,int r0,int c0,vector<vector<int>> &g,string &path){\n        if (r<0||c<0||r>=rows||c>=cols||g[r][c]!=1) return;\n        g[r][c]=0;\n        path += \"(\" + to_string(r-r0) + \",\" + to_string(c-c0) + \")\";\n        dfs(r+1,c,r0,c0,g,path); dfs(r-1,c,r0,c0,g,path);\n        dfs(r,c+1,r0,c0,g,path); dfs(r,c-1,r0,c0,g,path);\n    };\n    for (int r=0;r<rows;++r) for (int c=0;c<cols;++c) {\n        if (grid[r][c]==1) {\n            string path;\n            dfs(r,c,r,c,grid,path);\n            shapes.insert(path);\n        }\n    }\n    return shapes.size();\n}\n",
    "rotting_oranges": "int orangesRotting(vector<vector<int>> grid) {\n    int rows=grid.size(), cols=grid[0].size();\n    queue<tuple<int,int,int>> q;\n    int fresh=0;\n    for (int r=0;r<rows;++r) for (int c=0;c<cols;++c) {\n        if (grid[r][c]==2) q.push({r,c,0});\n        else if (grid[r][c]==1) fresh++;\n    }\n    int mins=0;\n    int dr[]={1,-1,0,0}, dc[]={0,0,1,-1};\n    while(!q.empty()){\n        auto [r,c,t] = q.front(); q.pop();\n        mins = max(mins, t);\n        for (int k=0;k<4;++k) {\n            int nr=r+dr[k], nc=c+dc[k];\n            if (nr>=0&&nr<rows&&nc>=0&&nc<cols&&grid[nr][nc]==1) {\n                grid[nr][nc]=2; fresh--; q.push({nr,nc,t+1});\n            }\n        }\n    }\n    return fresh==0 ? mins : -1;\n}\n",
    "meeting_rooms_ii": "int minMeetingRooms(vector<vector<int>> intervals) {\n    vector<int> starts, ends;\n    for (auto &iv : intervals) { starts.push_back(iv[0]); ends.push_back(iv[1]); }\n    sort(starts.begin(), starts.end());\n    sort(ends.begin(), ends.end());\n    int rooms=0, endPtr=0;\n    for (int s : starts) {\n        if (s < ends[endPtr]) rooms++;\n        else endPtr++;\n    }\n    return rooms;\n}\n",
    "min_rounds_complete_tasks": "int minimumRounds(vector<int> tasks) {\n    unordered_map<int,int> cnt;\n    for (int t : tasks) cnt[t]++;\n    int rounds=0;\n    for (auto &[k,c] : cnt) {\n        if (c==1) return -1;\n        rounds += (c + 2) / 3;\n    }\n    return rounds;\n}\n",
    "evaluate_rpn": "int evalRPN(vector<string> tokens) {\n    vector<int> stack;\n    for (auto &t : tokens) {\n        if (t==\"+\"||t==\"-\"||t==\"*\"||t==\"/\") {\n            int b=stack.back(); stack.pop_back();\n            int a=stack.back(); stack.pop_back();\n            if (t==\"+\") stack.push_back(a+b);\n            else if (t==\"-\") stack.push_back(a-b);\n            else if (t==\"*\") stack.push_back(a*b);\n            else stack.push_back(a/b);\n        } else {\n            stack.push_back(stoi(t));\n        }\n    }\n    return stack.back();\n}\n",
    "making_a_large_island": "int largestIsland(vector<vector<int>> grid) {\n    int n = grid.size();\n    int islandId = 2;\n    unordered_map<int,int> sizes;\n    int dr[]={1,-1,0,0}, dc[]={0,0,1,-1};\n    for (int r=0;r<n;++r) for (int c=0;c<n;++c) {\n        if (grid[r][c]==1) {\n            vector<pair<int,int>> stack = {{r,c}};\n            grid[r][c]=islandId;\n            int size=0;\n            while(!stack.empty()){\n                auto [cr,cc]=stack.back(); stack.pop_back();\n                size++;\n                for (int k=0;k<4;++k) {\n                    int nr=cr+dr[k], nc=cc+dc[k];\n                    if (nr>=0&&nr<n&&nc>=0&&nc<n&&grid[nr][nc]==1) {\n                        grid[nr][nc]=islandId; stack.push_back({nr,nc});\n                    }\n                }\n            }\n            sizes[islandId]=size; islandId++;\n        }\n    }\n    int best=0;\n    for (auto &[k,v] : sizes) best=max(best,v);\n    bool hasZero=false;\n    for (int r=0;r<n;++r) for (int c=0;c<n;++c) {\n        if (grid[r][c]==0) {\n            hasZero=true;\n            set<int> seen;\n            int total=1;\n            for (int k=0;k<4;++k) {\n                int nr=r+dr[k], nc=c+dc[k];\n                if (nr>=0&&nr<n&&nc>=0&&nc<n) {\n                    int id=grid[nr][nc];\n                    if (id>1 && !seen.count(id)) { seen.insert(id); total+=sizes[id]; }\n                }\n            }\n            best=max(best,total);\n        }\n    }\n    if (!hasZero) return n*n;\n    return best;\n}\n",
    "word_break_ii": "vector<string> wordBreakSentences(string s, vector<string> wordDict) {\n    unordered_set<string> wordSet(wordDict.begin(), wordDict.end());\n    unordered_map<int, vector<string>> memo;\n    function<vector<string>(int)> backtrack = [&](int start) -> vector<string> {\n        if (start == (int)s.size()) return {\"\"};\n        if (memo.count(start)) return memo[start];\n        vector<string> res;\n        for (int end=start+1; end<=(int)s.size(); ++end) {\n            string word = s.substr(start, end-start);\n            if (wordSet.count(word)) {\n                for (auto &rest : backtrack(end)) {\n                    res.push_back(rest.empty() ? word : word + \" \" + rest);\n                }\n            }\n        }\n        memo[start] = res;\n        return res;\n    };\n    return backtrack(0);\n}\n",
    "median_data_stream_doubled": "vector<int> medianStreamDoubled(vector<int> nums) {\n    priority_queue<int> small;\n    priority_queue<int, vector<int>, greater<int>> large;\n    vector<int> res;\n    for (int num : nums) {\n        small.push(num);\n        large.push(small.top()); small.pop();\n        if (large.size() > small.size()) { small.push(large.top()); large.pop(); }\n        if (small.size() > large.size()) res.push_back(2*small.top());\n        else res.push_back(small.top() + large.top());\n    }\n    return res;\n}\n",
}


def main():
    ids = sorted(f[:-5] for f in os.listdir(PROB_DIR) if f.endswith(".json"))
    fail_count = 0
    for pid in ids:
        with open(os.path.join(PROB_DIR, f"{pid}.json")) as f:
            problem = json.load(f)

        for lang, ref_map in [("python", REFERENCE_PY), ("cpp", REFERENCE_CPP)]:
            code = ref_map[pid]
            res = runner.run(lang, code, problem)
            status = "OK" if res.all_passed else "FAIL"
            if status == "FAIL":
                fail_count += 1
            print(f"[{status}] {pid:32s} {lang:7s} {res.passed}/{res.total}  "
                  f"compiled={res.compiled} err={res.runtime_error[:80] if res.runtime_error else ''}"
                  f"{res.compile_error[:200] if res.compile_error else ''}")
            if status == "FAIL":
                for c in res.cases:
                    if not c["passed"]:
                        print("    case", c["index"], c["input_display"], "expected=", c["expected"], "actual=", c["actual"])

    print("\nTotal failures:", fail_count)
    sys.exit(1 if fail_count else 0)


if __name__ == "__main__":
    main()
